# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forming_GRP.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GRP(object):
    def setupUi(self, GRP):
        GRP.setObjectName("GRP")
        GRP.resize(533, 326)
        GRP.setStyleSheet("\n"
"QPushButton{\n"
"background-color: grey;\n"
"width:100px;\n"
"length:200px;\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"border:none;\n"
"text-align:center;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:silver;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(96, 255, 39);\n"
"}\n"
"QLabel{\n"
"\n"
"width:100px;\n"
"length:200px;\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"border:none;\n"
"text-align:center;\n"
"}\n"
"\n"
"QTextEdit{\n"
"width:100px;\n"
"length:200px;\n"
"font-size: 14px;\n"
"}\n"
"")
        self.gridLayoutWidget = QtWidgets.QWidget(GRP)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 60, 471, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(GRP)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 160, 180, 122))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.label_6 = QtWidgets.QLabel(GRP)
        self.label_6.setGeometry(QtCore.QRect(100, 20, 311, 21))
        self.label_6.setStyleSheet("background-color: rgb(121, 255, 239)")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(GRP)
        QtCore.QMetaObject.connectSlotsByName(GRP)

    def retranslateUi(self, GRP):
        _translate = QtCore.QCoreApplication.translate
        GRP.setWindowTitle(_translate("GRP", "Form"))
        self.label_2.setText(_translate("GRP", "Импорт ГТМ:"))
        self.label_3.setText(_translate("GRP", "Импорт координат:"))
        self.label.setText(_translate("GRP", "Импорт фраклиста:"))
        self.pushButton.setText(_translate("GRP", "Импортировать"))
        self.pushButton_2.setText(_translate("GRP", "Импортировать"))
        self.pushButton_3.setText(_translate("GRP", "Импортировать"))
        self.label_4.setText(_translate("GRP", "Выполнить обработку:"))
        self.pushButton_4.setText(_translate("GRP", "Выполнить!"))
        self.label_5.setText(_translate("GRP", "Экспорт файла:"))
        self.pushButton_5.setText(_translate("GRP", "Экспортировать"))
        self.label_6.setText(_translate("GRP", "Формирование вкладки ГРП из NGT Smart"))
